spring:
  application:
    name: wising
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/wising}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:gnpp}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 1234
management:
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      show-details: always
jwt:
  secret-key: ${SECRET_KEY}
  expired:
    access: 3_600_000
    refresh: 300_000_000